### ISSUE TITLE
Need a mkdir -p before touch on the file

### ISSUE THREAD

**Issue by bdavj** [fire1ce/UDM-Persistent-SSH-Keys#4]
https://github.com/fire1ce/UDM-Persistent-SSH-Keys/blob/4571f431611b71238442e5a7fdc7f4a1a6d6197e/install.sh#L11

/mnt/data/ssh appears not to be created by default, causing the touch command to fail

**Comment by fire1ce** [comment]
Thanks. Fix at [46166b2](https://github.com/fire1ce/UDM-Persistent-SSH-Keys/commit/46166b2de913cf7760cd7a72459cdc257b03d21f)
